### PR TITLE
feat: open settings links

### PR DESCRIPTION
**Pull request by AlgyJr**
Adds openable links feature to settings screen links

Resolves: #461

### CODE REVIEW

**Comment by AbdullahAhmedSoomro** [comment]
@AlgyJr  Please go through readme.md the second last section which describes how to name a branch

**Comment by AbdullahAhmedSoomro** [comment]
So thats why i am closing this PR

**Comment by AlgyJr** [comment]
> @AlgyJr Please go through readme.md the second last section which describes how to name a branch

Sorry, do you want me to name it exactly the same name?
I'm asking that because my branch `feature/SettingsLinks` follow the name structure.

**Comment by AbdullahAhmedSoomro** [comment]
it will be `bug/SettingLink`

**Comment by AlgyJr** [comment]
> it will be `bug/SettingLink`

Understood, I didn't thought it is a bug 😅

**Pull request closed without merging**
