### PR TITLE
Update CONTRIBUTING.md

### LINKED ISSUE #485: Change Project Issue link
**In Contributing.md**
Replace this: https://github.com/hashirshoaeb/star_book/issues/new with this: https://github.com/Blocship/star_book/issues/new

### PR DESCRIPTION
**Pull request by Redvey**
Pull Request Description:
This pull request addresses the following changes in the project's documentation:

Replaces the GitHub issues link in CONTRIBUTING.md from "https://github.com/hashirshoaeb/star_book/issues" to "https://github.com/Blocship/star_book/issues".
This change aligns the documentation with the correct GitHub repository and will help users and contributors navigate to the correct location for reporting issues and seeking help.

Closes Issues:
Closes #485

### CODE REVIEW

**Comment by AbdullahAhmedSoomro** [comment]
@Redvey Bro i mentioned you in your previous PR that one PR for one issue you changed the link in two different places the second link you changed is from different issue which is #486  Help Needed Section and also please go through Contributing in Readme.md for branch naming. Here you can see:
image

I am closing this PR too

**Comment by Redvey** [comment]
@AbdullahAhmedSoomro I misjudged your statement, I am raising a new PR for issue #486

**Comment by AbdullahAhmedSoomro** [comment]
No issue, let me know if you need any guidance from me

**Comment by Redvey** [comment]
@AbdullahAhmedSoomro Hello there, I created a new branch called new feature where I solved the #485 issue. So do I need to create another new branch to commit #486 changes?

**Comment by AbdullahAhmedSoomro** [comment]
Hey, I accepted your PR but the branch name is not correct for the issue, it is my mistake that I didn't guide you properly, let me just explained it so that you can make correct PRs for this project. So if the issue is related to documentation like the changes is in readme.md or Contibuting.md there is a branch named `doc` you have to make PR that merge into `doc` branch not in `dev`, basically all issues related to documentation will be merged in to `doc` branch, and the name of the branch for issue will be like this `doc/helpNeededDoc`  or `helpNeededDoc` for issue #486, and yes you have to work on new branch for new issue, any query or confusion regarding this feel free to ask.
Thanks alot for your contribution!

**Comment by Redvey** [comment]
Thank you so much, now I will try to make the perfect PR

**Pull request closed without merging**
