### PR TITLE
fix Issue#465

### PR DESCRIPTION
**Pull request by ayushsingh01042003**
Hey I changed the link 'https://github.com/Blocship/star_book/blob/dev/PRIVACY%26POLICY.md' to this 'https://qurantalk.notion.site/Privacy-Policy-for-Starbook-Mobile-App-a8fb153c39dd45dfa5b2cb9a945e3c84?pvs=4' in the links.dart folder.
Let me know if this is Good!

### CODE REVIEW

**Comment by AbdullahAhmedSoomro** [comment]
@ayushsingh01042003, You changed the url launcher link, that was not the issue, you have to copy the content from this link https://qurantalk.notion.site/Privacy-Policy-for-Starbook-Mobile-App-a8fb153c39dd45dfa5b2cb9a945e3c84?pvs=4 and paste that content here https://github.com/Blocship/star_book/blob/dev/PRIVACY%26POLICY.md and use this link in url launcher. And feel free to ask for more information if the issue is still not clear to you.

**Comment by AbdullahAhmedSoomro** [comment]
@ayushsingh01042003 Please go through Contributing.md because your Pull request is not meeting the requirements

**Comment by ayushsingh01042003** [comment]
@AbdullahAhmedSoomro  so what I understand is that i need to copy the contents of this link https://qurantalk.notion.site/Privacy-Policy-for-Starbook-Mobile-App-a8fb153c39dd45dfa5b2cb9a945e3c84?pvs=4 and paste it in the PRIVACY&POLICY.md file of the project and nothing else. Is that correct?

**Comment by AbdullahAhmedSoomro** [comment]
@ayushsingh01042003 yes

**Pull request closed without merging**
