### PR TITLE
resolves #465

### LINKED ISSUE #465: Add privacy and terms
image

### PR DESCRIPTION
**Pull request by ayushsingh01042003**
I made the suggested changes by modifying the `PRIVACY.POLICY.md` file of the repo and adding the contents from the link https://qurantalk.notion.site/Privacy-Policy-for-Starbook-Mobile-App-a8fb153c39dd45dfa5b2cb9a945e3c84?pvs=4 to it.
Please let me know if this is correct.

### CODE REVIEW

**Comment by AbdullahAhmedSoomro** [comment]
Yes, it's correct but I mentioned you earlier in a previous Pull Request that you created,
Please go through Contributing.md because your Pull request does not meet the requirements.
Therefore I am closing this pull request too. Check how to name a branch for an issue.

**Comment by ayushsingh01042003** [comment]
@AbdullahAhmedSoomro I was unable to find anything regarding how to name a branch in `CONTRIBUTING.md` so could you please tell me how do I name the branch and commit message for this Issue or let me know where the instructions are written for the same

**Comment by AbdullahAhmedSoomro** [comment]
I apologize for my mistake it was in Readme.md not in Contributing.md, 
here you can see, how to name the branch:
image

**Comment by ayushsingh01042003** [comment]
So shall i name it as feature/Privacy&Terms and commit as "Update Privacy&Policy.md" would that be good ?

**Comment by AbdullahAhmedSoomro** [comment]
Yup

**Pull request closed without merging**
